# action to dec
dataset: GTA
model_name: Path_GRU
model_specs:
  n_feats_mlp: 1024
  n_feats_gru: 5120
  n_feats_unet_mlp: 1024
  n_feats_unet: 32
  train_pathnet: true
  train_posenet: true
  traj_interp: true

dataset_specs:
  n_hist: 15
  n_pred: 15
  n_joints: 21
  data_file: ../data/GTA-IM-Dataset-processed/
  random_rot: true
  max_dist_from_human: 2.5
  num_scene_points: 20000
  step: 1
  sigma: 0.2

  root_idx: 14
  left_hip_idx: 15
  right_hip_idx: 18

  # Environment information as input.
  use_raw_obs: false
  use_env_pcd: false
  use_map: true
  use_traj_map: true
  use_pose_gt: true
  map_size: 40
  z_min: -1.0
  z_max: 0.5
  z_floor: -0.3

loss:
  use_pose: true
  use_traj: true
  use_final_pos: true
  use_traj_map: true
  use_collision: true

  weight_pose: 1
  weight_traj: 1
  weight_final_pos: 1
  weight_traj_map: 1.0
  weight_collision: 1.0
  weight_bce: 40.0

mode: train

lr: 0.0001
lr_step_size: 600
lr_gamma: 0.1
num_epoch_fix: 1
save_freq: 300
